# Generated by Django 5.0.6 on 2024-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('sentiment_score', models.FloatField()),
                ('trends', models.CharField(max_length=255)),
            ],
        ),
    ]
